---
# tasks file for forwarding

- name: "fail if Operating System is not CentOS-7.x"
  fail: msg="Operating System {{ ansible_distribution }}-{{ ansible_distribution_version }} not supported"
  when: (ansible_distribution != "CentOS" and ansible_distribution != "RedHat") or ansible_distribution_major_version != "7"

- name: check if cpu support virtualization
  shell: grep -E '(vmx|svm)' /proc/cpuinfo
  register: cpu_support_vt
  ignore_errors: true

- name: fail if cpu do not support virtualization
  fail: msg="cpu do not support virtualization, stop installing"
  when: cpu_support_vt | failed

- name: install kvm on CentOS
  include: centos.yml


